---
title: "Acute Stroke Paper Supplemental Results"
author: Eckhard Schlemm
output:   
    redoc::redoc:
    highlight_output: FALSE
#output: bookdown::html_document2
#output: html_document
always_allow_html: yes
---

```{r include=FALSE}
require(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```
  
```{r}
tab.clin <- data.clinical_long %>% 
  ungroup() %>% 
  select(ID, numID, age, gender, Stroke.side,vol, clin.meas.name, clin.meas.value, tp) %>% 
  merge(data.GGP  %>% 
          ungroup() %>% 
          select(numID, tp, threshold, side, lab, GGP)
        ) %>% 
  filter(threshold == 1, ID %in% data.patients$ID & clin.meas.name %in% c('rGS','NIHSS', 'FM') & lab %in% c(1,3)) %>% 
  select(ID, age, gender, Stroke.side, vol, tp, clin.meas.name, clin.meas.value, side, lab, GGP) %>% 
  arrange(ID, tp)

tab.clin$clin.meas.value[is.nan(tab.clin$clin.meas.value)] <- NA
tab.clin$GGP[is.nan(tab.clin$GGP)] <- NA

tab.clin %>% 
  mutate(lab = as_labeller(GGP_names)(lab)[[1]]) %>% 
  rename('GGP.value' = 'GGP', 'GGP.name' = 'lab') %>% 
  write.csv(file = 'tab.clin.csv', row.names = FALSE)


tab.clin %>% 
  gather(variable, value, GGP) %>% 
  unite(temp, lab, side, variable) %>% 
  spread(temp, value) %>%
  gather(variable, value, clin.meas.value) %>% 
  unite(temp, clin.meas.name, variable) %>% 
  spread(temp, value) %>%
  select(ID, age, gender, Stroke.side, vol, tp
         , NIHSS_clin.meas.value, FM_clin.meas.value, rGS_clin.meas.value
         , `1_Left_GGP`, `3_Left_GGP`, `1_Right_GGP`, `3_Right_GGP`) %>% 
  flextable() %>% 
  add_header_row(values = c('ID', 'Age', 'Sex','Stroke side', 'Lesion volume', 'Time'
                            , 'NIHSS', 'FM', 'rGS'
                            , 'Left Hemisphere', 'Right Hemisphere'
                            )
                 , colwidths = c(1,1,1,1,1,1,1,1,1,2,2)) %>% 
  set_header_labels(values = list(ID = 'ID'
                                  , age = 'Age'
                                  , gender = 'Sex'
                                  , Stroke.side = 'Stroke side'
                                  , vol = 'Lesion volume'
                                  , tp = 'Time'
                                  , `1_Left_GGP` = 'Efficiency'
                                  , `1_Right_GGP` = 'Efficiency'
                                  , `3_Left_GGP` = 'Modularity'
                                  , `3_Right_GGP` = 'Modularity'
                                  , `FM_clin.meas.value` = 'FM'
                                  , `NIHSS_clin.meas.value` = 'NIHSS'
                                  , `rGS_clin.meas.value` = 'rGS'
                                  )) %>% 
  merge_v(part = 'body', j = c(1,2,5,6,10,11,12)) %>% 
  merge_v(part = 'header') %>%
  flextable::theme_vanilla()
```